### ISSUE TITLE
書的來源

### ISSUE THREAD

**Issue by caasi** [cschat-tw/StudyGroup-TAPL#1]
已知的來源：
- 謎之 pdf
- 實體書
- 二手實體書
- Kindle 版

現在實體書的價格是 $2793 NTD ，天瓏目前沒書。

**Comment by shhyou** [comment]
二手實體書 amazon 會賣海外嗎? 二手的開學季才會比較便宜 現在已錯過QQ

**Comment by drm343** [comment]
可以把這個列為 NP 問題嗎?

總之書本的部份不強求啦，有是比較好，沒有可能就只好謎之 PDF 什麼的了

**Comment by ghost** [comment]
好像有公佈 final draft 的樣子

**Comment by shhyou** [comment]
有 draft 的是 PFPL?

**Comment by ghost** [comment]
是 TSPL

**Comment by ghost** [comment]
draft 書名不同，但是是同一本書

**Comment by shhyou** [comment]
有 draft 連結嗎? 
http://www.cs.cmu.edu/~rwh/misc/tspl.pdf 這個作者是 Robert Harper, 內容也不對@@

**Comment by ghost** [comment]
http://ropas.snu.ac.kr/~kwang/520/pierce_book.pdf

**Comment by shhyou** [comment]
So nice!
wow, 除了少了一些東西以外, 也有些本篇裡面沒有的章節耶XD notation, bounded quantification, kinding, higher-order subtyping 等等

**Comment by drm343** [comment]
看起來書的問題可以先用 final 解決，看起來也蠻 ok 的，畢竟只有少數人有書也蠻麻煩的
