### ISSUE TITLE
決定舉行方式

### ISSUE THREAD

**Issue by caasi** [cschat-tw/StudyGroup-TAPL#2]
線上或線下？錄影或文字直播？

**Comment by shhyou** [comment]
/me 只能線上參加
考慮到大家可能要寫 code 寫 typing rules, 文字直播有辦法插入這類圖嗎?

**Comment by caasi** [comment]
@drm343 提到：

`12:20 <yulin> 高雄這邊先暫定 11/28 線下讀書可以嗎?`

**Comment by drm343** [comment]
高雄這邊先暫定 11/28 線下吧，地點我來找找看，可能會先暫定彩巴之類的點

**Comment by shhyou** [comment]
賀高雄開辦XD

**Comment by drm343** [comment]
如果要錄影，那我要另外找個好一點的地點，避免被干擾，文字轉播是比較簡單，是不是要另外考慮轉播工具？如果用 irc 就會遇到沒辦法插圖的狀況，變成要先丟別的地方上傳完再轉貼 irc

來投票決定是要影音轉播還是文字轉播吧。

**Comment by shhyou** [comment]
鍵盤轉播一票 方便搜尋討論

**Comment by caasi** [comment]
鍵盤轉播一票

**Comment by shhyou** [comment]
但是插圖這部份我在想不知道有沒有比較好的方法 大家用 hackpad 轉播如何?
hackpad 可以用聊天型式, 好像也可以放入圖片, 只是不知道方不方便(能不能直接複製貼上)
irc 最大優點大概是輕量吧, hackpad 有時候卡卡的說

**Comment by CindyLinz** [comment]
hackpad 的複製貼上... 是 undeterministic style :Q
gitter 聊天應該也是要自己先找地方上傳圖檔, 然後可以 embed 顯示出來. 但不方便整理文件
slack 可以直接上傳圖檔, 不過路人加入比較麻煩, 舊 log 會被刪掉...

2015-11-19 11:48 GMT+08:00 suhorng notifications@github.com:

**Comment by drm343** [comment]
telegram 不適合寫文件，不然我還蠻想投 telegram 一票

**Comment by drm343** [comment]
文件的部份請轉移至 https://github.com/cschat-tw/StudyGroup-TAPL/issues/4 進行後續討論。
