### ISSUE TITLE
線下參加報名

### ISSUE THREAD

**Issue by drm343** [cschat-tw/StudyGroup-TAPL#3]
時間先暫定 11/28 14:00 ~ 17:30 或 18:00，
因為時間還不確定會多久，可以提前結束，
暫定地點是彩巴，等等我會去問問這邊的地點怎麼申請，
請有興趣的人先往下報名，格式還沒確定啦。

忘記補上日期
難道真的要 functional everyday?

**Comment by drm343** [comment]
報名者：一卡
附註：我先當第一號報名者了

**Comment by b4284** [comment]
報名者：b4283

**Comment by drm343** [comment]
目前線下會議加上我只有三個人，所以先不去借那些比較大的場地喔。

以下彩巴參考點，如果有其他點想推荐，請補充，謝謝。
1. 813高雄市左營區富民路391號
2. 807高雄市三民區、高雄市三民區澄清路542號
3. 801高雄市前金區中華三路211號

**Comment by descent** [comment]
請問日期是?

2015-11-20 14:37 GMT+08:00 Yu-Lin notifications@github.com:

**Comment by drm343** [comment]
11/28 14:00 ~ 17:30 或 18:00

**Comment by descent** [comment]
看完這個後
http://www.khcc.gov.tw/home02.aspx?ID=$5101&IDK=2&EXEC=D&DATA=35806&AP=$5101_HISTORY-0
可以過去

**Comment by drm343** [comment]
地點先暫定 1. 813高雄市左營區富民路391號 喔

**Comment by caasi** [comment]
雞婆幫補報名連結： [#1 Types and Programming Language 第一次線下討論會](http://tapl.kktix.cc/events/d79d3108?preview_token=fdc97a60403e9af9916c365e776f980f)

**Comment by berget** [comment]
這次駁二FF有いとうかなこ！！！
